# inspiration from https://github.com/python-trio/trio-mysql

# our op wants to run under standard privs (no sudo)
# https://stackoverflow.com/q/40661470/4036945

#sudo: required

# we'll use python (because that's what i'm using anyway!)

language: python
python:
  - "3.6"

#  pip?
cache: 
  directories:
    - $HOME/.mysql_dl_tars
    - $HOME/mysql.5.6.40

#matrix:
#  include:
#    - addons:
#        mariadb: 5.5
#        python: "3.6"
#
#    - addons:
#        mariadb: 10.1
#        python: "3.6"
#
#    - python: "3.6"
#      env: CHECK_DOCS=1

# different py version from 5.6 and 5.7 as cache seems to be based on py version
# http://dev.mysql.com/downloads/mysql/5.7.html has latest development release version
# really only need libaio1 for DB builds however libaio-dev is whitelisted for container builds and liaio1 isn't
#  - export PASSWORD=travis;
#  - pip install -U pytest pytest-trio pytest-cov coverage

# we'll have zeromq & libsodium, thanks
install:
  - pip install -U pysodium pyzmq

before_script:
  - echo 'before script'
  - ps -ef
#  - mysqld --verbose --help

  # not the nicest thing to do over and over? cache instead?
  # (my test showed a download speed of ~50 megabytes per second - proxy?)
  # (well that was my first test - fluke? - subsequent ones were a lot slower!)
  - if [ ! -d "$HOME/.mysql_dl_tars" ]; then mkdir "$HOME/.mysql_dl_tars"; fi
  - pushd "$HOME/.mysql_dl_tars"
  - if [ ! -f 'mysql-5.6.40-linux-glibc2.12-x86_64.tar.gz' ]; then wget -c -d 'https://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.40-linux-glibc2.12-x86_64.tar.gz'; fi
  - popd

  # unpack
  # - thanks to https://superuser.com/q/311301 and
  # - http://www.bluecrownsoftware.com/article/271/Installing-MySQL-without-Root-Access-on-Linux
  - if [ ! -d "$HOME/mysql.5.6.40" ]; then mkdir "$HOME/mysql.5.6.40"; fi
  - pushd "$HOME/mysql.5.6.40"
  - export TCI_D_MYSQL_ROOT=$(pwd)
  - tar --gzip --extract --skip-old-files --directory="$TCI_D_MYSQL_ROOT" --file="$HOME/.mysql_dl_tars/mysql-5.6.40-linux-glibc2.12-x86_64.tar.gz"
  - pushd "$TCI_D_MYSQL_ROOT/mysql-5.6.40-linux-glibc2.12-x86_64"
  - export TCI_D_MYSQL=$(pwd)
  - echo "$TCI_D_MYSQL_ROOT"
  - echo "$TCI_D_MYSQL"
  
  # write the cnf file
  - echo '[server]'                                    > "$TCI_D_MYSQL_ROOT/my.cnf"
  - echo "basedir=$TCI_D_MYSQL"                        >> "$TCI_D_MYSQL_ROOT/my.cnf"
  - echo "datadir=$TCI_D_MYSQL/data"                   >> "$TCI_D_MYSQL_ROOT/my.cnf"
  - echo "log-error=$TCI_D_MYSQL_ROOT/mysql.err"       >> "$TCI_D_MYSQL_ROOT/my.cnf"
  - echo "pid-file=$TCI_D_MYSQL_ROOT/mysql.pid"        >> "$TCI_D_MYSQL_ROOT/my.cnf"
  - echo 'socket=/tmp/.thesock'                        >> "$TCI_D_MYSQL_ROOT/my.cnf"
  - echo 'port=3666'                                   >> "$TCI_D_MYSQL_ROOT/my.cnf"
  - cat "$TCI_D_MYSQL_ROOT/my.cnf"

  # perform the instal
  - pushd "$TCI_D_MYSQL/scripts/"
  - if [ -f 'mysql_install_db' ]; then echo Will run ./mysql_install_db --defaults-file="$TCI_D_MYSQL_ROOT/my.cnf"; fi
  - if [ -f 'mysql_install_db' ]; then ./mysql_install_db --defaults-file="$TCI_D_MYSQL_ROOT/my.cnf"; fi
#  - if [ -f 'mysql_install_db' ]; then ./mysql_install_db --basedir="$TCI_D_MYSQL" --datadir="$TCI_D_MYSQL/data" --log-error="$TCI_D_MYSQL_ROOT/mysql.err" --pid-file="$TCI_D_MYSQL_ROOT/mysql.pid" --socket="$TCI_D_MYSQL_ROOT/thesock"; fi
  - popd

script:
#  - .travis/run.sh
  - echo 'script'
# - ./bin/mysqld --basedir="$HOME/mysql.1" --datadir="$TCI_D_MYSQL/data" --log-error="$HOME/mysql.1/mysql.err" --pid-file="$HOME/mysql.1/mysql.pid" --socket="$HOME/mysql.1/thesock" --port=3306 &
#  - sleep 30
# - ./bin/mysqladmin --socket="$HOME/mysql.1/thesock" shutdown

#  - ./bin/mysql --socket=[Base MySQL Directory]/thesock

after_success:
  - echo 'after success'

after_failure:
  - echo 'after failure'

# vim: sw=2 ts=2 sts=2 expandtab
