# inspiration from https://github.com/python-trio/trio-mysql

# remember - our op wants to run under standard privs (no sudo)
# https://stackoverflow.com/q/40661470/4036945
#sudo: required

# we'll use python (because that's what i'm using anyway!)

language: python
python:
  - "3.6"

#  pip?
cache: 
  directories:
    - $HOME/.mysql_dl_tars
    - $HOME/mysql.5.6.40

# we'll have zeromq & libsodium, thanks
install:
  - pip install -U pysodium pyzmq

before_script:
  - echo 'before script'
  - ps -ef

  # not the nicest thing to do over and over? cache instead?
  # (my test showed a download speed of ~50 megabytes per second - proxy?)
  # (well that was my first test - fluke? - subsequent ones were a lot slower!)
  - if [ ! -d "$HOME/.mysql_dl_tars" ]; then mkdir "$HOME/.mysql_dl_tars"; fi
  - pushd "$HOME/.mysql_dl_tars"
  - if [ ! -f 'mysql-5.6.40-linux-glibc2.12-x86_64.tar.gz' ]; then wget -c -d 'https://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.40-linux-glibc2.12-x86_64.tar.gz'; fi
  - popd

  # unpack & instal non-root, standalone mysqld
  # - thanks to: https://superuser.com/q/311301, https://superuser.com/a/447498 and
  # - http://www.bluecrownsoftware.com/article/271/Installing-MySQL-without-Root-Access-on-Linux
  - if [ ! -d "$HOME/mysql.5.6.40" ]; then mkdir "$HOME/mysql.5.6.40"; fi
  - pushd "$HOME/mysql.5.6.40"
  - export TCI_D_MYSQL_ROOT=$(pwd)
  - if [ ! -d "$TCI_D_MYSQL_ROOT/mysql-5.6.40-linux-glibc2.12-x86_64" ]; then tar --gzip --extract --skip-old-files --directory="$TCI_D_MYSQL_ROOT" --file="$HOME/.mysql_dl_tars/mysql-5.6.40-linux-glibc2.12-x86_64.tar.gz"; fi
  - pushd "$TCI_D_MYSQL_ROOT/mysql-5.6.40-linux-glibc2.12-x86_64"
  - export TCI_D_MYSQL=$(pwd)
  - echo "$TCI_D_MYSQL_ROOT"
  - echo "$TCI_D_MYSQL"

  # delete the error log
  - echo date > "$TCI_D_MYSQL_ROOT/mysql.err"

  # write a fresh cnf file at each start
  - echo '[server]'                                    > "$TCI_D_MYSQL_ROOT/my.cnf"
  - echo "basedir=$TCI_D_MYSQL"                        >> "$TCI_D_MYSQL_ROOT/my.cnf"
  - echo "datadir=$TCI_D_MYSQL/data"                   >> "$TCI_D_MYSQL_ROOT/my.cnf"
  - echo "log-error=$TCI_D_MYSQL_ROOT/mysql.err"       >> "$TCI_D_MYSQL_ROOT/my.cnf"
  - echo "pid-file=$TCI_D_MYSQL_ROOT/mysql.pid"        >> "$TCI_D_MYSQL_ROOT/my.cnf"
  - echo 'socket=/tmp/.thesock'                        >> "$TCI_D_MYSQL_ROOT/my.cnf"
  - echo 'port=3666'                                   >> "$TCI_D_MYSQL_ROOT/my.cnf"
  - cat "$TCI_D_MYSQL_ROOT/my.cnf"

  # perform the instal
  # --basedir="$TCI_D_MYSQL" --datadir="$TCI_D_MYSQL/data" --log-error="$TCI_D_MYSQL_ROOT/mysql.err" --pid-file="$TCI_D_MYSQL_ROOT/mysql.pid" --socket="$TCI_D_MYSQL_ROOT/thesock"
  - pushd "$TCI_D_MYSQL/"
  - if [ -f 'scripts/mysql_install_db' ]; then echo Will run ./scripts/mysql_install_db --defaults-file="$TCI_D_MYSQL_ROOT/my.cnf"; fi
  - if [ -f 'scripts/mysql_install_db' ]; then ./scripts/mysql_install_db --defaults-file="$TCI_D_MYSQL_ROOT/my.cnf"; fi
  - popd

script:
  - echo 'script'
  - pushd "$TCI_D_MYSQL/"
  - bin/mysqld --defaults-file="$TCI_D_MYSQL_ROOT/my.cnf" --socket=/tmp/.thesock &
  - sleep 10
  - cat "$TCI_D_MYSQL_ROOT/mysql.pid"
  - bin/mysqladmin --defaults-file="$TCI_D_MYSQL_ROOT/my.cnf" --socket=/tmp/.thesock ping
  - ps -ef
  - ls -lasht /tmp
  - export TCI_MYSQL_PID_1="`cat $TCI_D_MYSQL_ROOT/mysql.pid`"
  # bin/mysqladmin --defaults-file="$TCI_D_MYSQL_ROOT/my.cnf" --socket=/tmp/.thesock shutdown
  - kill -SIGTERM $TCI_MYSQL_PID_1
  - sleep 10
  - if [ -f '/tmp/.thesock' ]; then bin/mysqladmin --defaults-file="$TCI_D_MYSQL_ROOT/my.cnf" --socket=/tmp/.thesock ping; fi
  - ps -ef
  - ls -lasht /tmp
  ##########################################
  - echo 'change your cnf here'
  ##########################################
  - bin/mysqld --defaults-file="$TCI_D_MYSQL_ROOT/my.cnf" --socket=/tmp/.thesock &
  - sleep 10
  - cat "$TCI_D_MYSQL_ROOT/mysql.pid"
  - bin/mysqladmin --defaults-file="$TCI_D_MYSQL_ROOT/my.cnf" --socket=/tmp/.thesock ping
  - ps -ef
  - ls -lasht /tmp
  - export TCI_MYSQL_PID_2="`cat $TCI_D_MYSQL_ROOT/mysql.pid`"
  # bin/mysqladmin --defaults-file="$TCI_D_MYSQL_ROOT/my.cnf" --socket=/tmp/.thesock shutdown
  - kill -SIGTERM $TCI_MYSQL_PID_2
  - sleep 10
  - if [ -f '/tmp/.thesock' ]; then cat "$TCI_D_MYSQL_ROOT/mysql.pid"; fi
  - if [ -f '/tmp/.thesock' ]; then bin/mysqladmin --defaults-file="$TCI_D_MYSQL_ROOT/my.cnf" --socket=/tmp/.thesock ping; fi
  - ps -ef
  - ls -lasht /tmp
  - echo 'Fin.'

after_success:
  - echo 'after success'
  - if [ -f '/tmp/.thesock' ]; then bin/mysqladmin --defaults-file="$TCI_D_MYSQL_ROOT/my.cnf" --socket=/tmp/.thesock ping; fi
  - ls -lasht "$TCI_D_MYSQL_ROOT"
  - ls -lasht "$TCI_D_MYSQL"
  - cat "$TCI_D_MYSQL_ROOT/mysql.err"

after_failure:
  - echo 'after failure'
  - ls -lasht /tmp
  - ls -lasht "$TCI_D_MYSQL_ROOT"
  - ls -lasht "$TCI_D_MYSQL"
  - cat "$TCI_D_MYSQL_ROOT/mysql.err"

# vim: sw=2 ts=2 sts=2 expandtab
